### ISSUE TITLE
customize element used for strike-throughs

### ISSUE THREAD

**Issue by binyamin** [remarkjs/remark-gfm#17]
### Customize element used for strike-throughs
In html, there are two elements for a strike-through. The `<s>` element denotes text which isn't applicable anymore ([mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s)). The `<del>` element is for document edits ([mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del)). Either use-case might apply with an input of `~~text~~`.

### Problem
This plugin currently produces `<del>` elements. I'm coming from markdown-it, and they use the `<s>` element for gfm strike-throughs. The `<s>` element seems to have a more general use-case, anyways. The example in the GFM spec is a `<del>` element, and that seems to be what the GitHub website uses.

### Expected behavior
Expose an option which allows the user to choose between the `<s>` and `<del>` elements.

### Alternatives
Just throwing it out there: single tildes are not part of the GFM spec. Once we're changing things up, we could make _single tildes_ become `<s>` elements and keep _double tildes_ the way they are.

**Comment by wooorm** [comment]
Hi there!

- This plugin has nothing to do with html. Whatever you're using to get to that, is where your question should go, and they probably already have answers
- The double tilde is indeed the spec, but github.com does not adhere to that spec. Most users want to adhere to how stuff worms on here, rather than matching a theoretical spec that nobody implements, and hence it's an option here!

**Comment by binyamin** [comment]
@wooorm Thanks, that makes sense.

You seem to be a nice maintainer. So, I thought you'd appreciate some feedback.

I understand why you closed this issue. However, I could see someone else thinking, "I put a lot of time & effort into writing a detailed issue, and they ned without a second thought". From one maintainer to another, I get that it's not usually possible to respond perfectly. I have some experience with endless amounts of issues which need to be triaged.

A good compromise may be to give _detailed issues_ a grace-period before closing them. Or, you could close them with a comment like, "feel free to follow-up with your thoughts". Just ideas. Cheers!

**Comment by ChristianMurphy** [comment]
@binyamin you're probably looking for the handlers option of https://github.com/syntax-tree/mdast-util-to-hast (or of one of it's wrappers, like remark-rehype). Which can be used to change the output of the [`delete` node](https://astexplorer.net/#/gist/6d53aa4162f8b52a9670e26e1fec7232/cc17b03c8da03d4664de7daab90ffe10b0f07d97) as a [hast node](https://github.com/syntax-tree/hast).

> Just throwing it out there: single tildes are not part of the GFM spec. Once we're changing things up, we could make single tildes become `<s>` elements and keep double tildes the way they are.

This repo follows the GFM spec, and does not intend to break with the spec,
If you're curious on context peruse the parser option bugs and questions from remark https://github.com/remarkjs/remark/issues?q=is%3Aissue+is%3Aclosed, customizing parsing with options tends to cause more confusion and bugs than it solves.
You are welcome to create a new parser variant for binyamin flavored markdown (in a similar approach to https://github.com/zestedesavoir/zmarkdown or https://github.com/mdx-js/mdx)

But as @wooorm this doesn't really make sense here, and the core part you seem to want to get at: changing the HTML tag, can already be done elsewhere in the unified ecosystem.

> A good compromise may be to give detailed issues a grace-period before closing them.

Generally we do, though we may have a threshold of what is considered detailed than you do.

**Comment by ChristianMurphy** [comment]
Also, if you're goal is by any chance related to parsing gemini.
https://github.com/wooorm/dioscuri may offer a more smooth experience than micromark/remark.

**Comment by binyamin** [comment]
@ChristianMurphy
> Also, if you're goal is by any chance related to parsing gemini.
https://github.com/wooorm/dioscuri may offer a more smooth experience than micromark/remark.

Thanks, I appreciate it. I've seen dioscuri, and I actually wrote [my own parser for gemini](https://github.com/gemium/gemium/blob/main/main/protocols/lib/tokenize.js), because I didn't want the ESM headache.

> This repo follows the GFM spec, and does not intend to break with the spec,

By the way, this repo supports single tildes, which is _not_ part of the GFM spec. My point was that, if we're breaking the spec with the tilde count, we could break it justify that by changing the element.

**Comment by ChristianMurphy** [comment]
> if we're breaking the spec with the tilde count, we could justify that by changing the element.

Whether it's diverging from the spec documented by GitHub, or the spec as implemented on GitHub, I'd be highly cautious adding more divergence/options here by splitting the `delete` type in two.
I'd also be cautious adding divergence to https://github.com/syntax-tree/mdast-util-to-hast by moving away from `del` which is used both in [the spec](https://github.github.com/gfm/#strikethrough-extension-) and implementation (~~example~~).

That said, I'm happy to help with questions around customizing for your use case.
GitHub Discussions often makes questions/discussions easier, as it has a proper threading mechanism which GitHub issues sadly lacks. Remark has discussions enabled at https://github.com/remarkjs/remark/discussions
