### ISSUE TITLE
<details> collapse is not supported

### ISSUE THREAD

**Issue by kyeotic** [remarkjs/remark-gfm#18]
### `<details>` not supported

Using of  `<details>` tags in GFM is supposed to create [collapse sections](https://docs.gitlab.com/ee/user/markdown.html#collapsible-section). By default this is not happening in react-markdown when gfm is added as a plugin, and I see no option to enable it.

### Your environment

*   **OS**: MacOS
*   **Packages**: React-markdown

### Steps to reproduce

1. Add this section to markdown

```
<details>
<summary> Title</summary>

Main Section
</details>
```
2. Add remark-gfm as react-markdown plugin

[Codesandbox reproduction](https://codesandbox.io/s/react-markdown-debug-forked-5j24u)

### Expected behavior

A collapsible should replace the `<details>` section

### Actual behavior

`<details` content is rendered as escaped string.

**Comment by ChristianMurphy** [comment]
The link you provided it to Git<b>Lab</b> not Git<b>Hub</b>
Details and collapse are not a part of GFM https://github.github.com/gfm/
They're plain HTML which can be supported with https://github.com/remarkjs/react-markdown#appendix-a-html-in-markdown

https://codesandbox.io/s/react-markdown-debug-forked-72z66

**Comment by kyeotic** [comment]
@ChristianMurphy I provided that link because the docs are better, but this _is_ part of GFM. Its even used in the [react-markdown](https://github.com/remarkjs/react-markdown) readme. Its listed in the [GFM Spec](https://github.github.com/gfm/#html-blocks)

> Start condition: line begins the string < or </ followed by one of the strings (case-insensitive) address, article, aside, base, basefont, blockquote, body, caption, center, col, colgroup, dd, details, dialog, dir, div, dl, dt, fieldset, figcaption, figure, footer, form, frame, frameset, h1, h2, h3, h4, h5, h6, head, header, hr, html, iframe, legend, li, link, main, menu, menuitem, nav, noframes, ol, optgroup, option, p, param, section, source, summary, table, tbody, td, tfoot, th, thead, title, tr, track, ul, followed by whitespace, the end of the line, the string >, or the string />.
End condition: line is followed by a blank line.

I'm sorry for the confusing links to gitlab, but this is most certainly part of the Git**Hub** markdown spec.

**Comment by ChristianMurphy** [comment]
> An HTML block is a group of lines that is treated as raw HTML (and will not be escaped in HTML output).

right, and remark-gfm does does that.
It puts the contents into an HTML block https://astexplorer.net/#/gist/35552bdcd50ad974284c7acd9437afaf/dcb1fc32ab8b2478d866003aefa2942f56f83f22
It is just the parser, not the part that translates to markdown to HTML (that's `remark-rehype`, and is part of `react-markdown` by default) or the part that takes raw HTML and parses it into an HTML abstract syntax tree (`rehype-raw` which can be included in `react-markdown` but is not by default).

**Comment by kyeotic** [comment]
remark-gfm is not producing the same output that github does when it takes the same markdown as input. Github produces a collapsible, remark-gfm produces plain text.

The output of remark-gfm on the README of react-markdown is not the same ouput that GitHub has.

**Comment by ChristianMurphy** [comment]
Again, `remark-gfm` does not produce HTML.

> The output of remark-gfm on the README of react-markdown is not the same ouput that GitHub has.

You are welcome to add `rehype-raw` and `rehype-santize` to the example if you want.

**Comment by kyeotic** [comment]
What does remark-gfm produce? When it sees github tables syntax the final output has an HTML table. remark-gfm might not produce that _directly_ but without remark-gfm the HTML is different, so it produces HTML _indirectly_.

I'd like to avoid adding those packages if possible. I expected remark-gfm to create an experience that was consistent with GitHub, and this delta seems like a bug to me. Whatever level of the unified pipeline this packages fits into it impacts the final HTML output based in the markdown contents, and it seems like the its trying to do that in a way thats consistent with GitHub.

Perhaps I misunderstand the goal of this package though.

**Comment by ChristianMurphy** [comment]
> What does remark-gfm produce?

an Abstract Syntax Tree https://unifiedjs.com/learn and https://github.com/syntax-tree/mdast

> remark-gfm might not produce that directly but without remark-gfm the HTML is different

Right, `remark-gfm` adds some additional markdown abstract syntax tree types  https://github.com/syntax-tree/mdast#gfm.
Which `remark-rehype` can interpret.

> I expected remark-gfm to create an experience that was consistent with GitHub, and this delta seems like a bug to me. 

It is consistent with how it is parsed on GitHub.

> Whatever level of the unified pipeline this packages fits into it impacts the final HTML output based in the markdown contents, and it seems like the its trying to do that in a way thats consistent with GitHub.

This handles `markdown -> mdast` and `mdast -> markdown`, it does both correctly.
`mdast -> hast` is handled by `remark-rehype`.

**Comment by kyeotic** [comment]
Gotcha, so any features of GitHub flavored markdown that require handling HTML tags are outside of this packages scope. It might be worth pointing out in the README that this package will not close the gap between CommonMark and the behavior of markdown when viewed on the GitHub site.

**Comment by wooorm** [comment]
@kyeotic the handling of details you see on github or gitlab has *nothing* to do with those platforms. It's markdown, commonmark, that handles HTML - GFM does nothing with them. You don't need remark-gfm for them.

**Comment by kyeotic** [comment]
Actually the more I think about this the less it makes sense. This whole unified pipeline that moves from markdown to AST to HTML is an architecture of remark, not of GitHub or GFM.

When GitHub sees a markdown file with tables and `<details>` its final result is a page with HTML tables and HTML `<details>`.

When `react-markdown` + `remark-gfm` see the same content they do not produce the same result.

All the intermediate steps (parsing, producing AST, generating HTML) are all ways remark has decided to slice the problem up. However if the final result is different than GitHub then why does it matter that the issue is with HTML or AST or markdown? Those steps are all _means to an end_, and `remark-gfm` arrives at a different end than GitHub.

The pipeline is modified by `remark-gfm` to support tables. Why can't it modify the pipeline to support `<details>`? Is it impossible to represent `<details>` with an AST? It is impossible to parse?

--- 
The delta still isn't closed by `rehype-raw`+ `rehype-santize` because GitHub blocks most HTML tags, and `rehype-raw` + `rehype-santize` lets most of them through. Perhaps another library designed to match GitHub's behavior is needed.

**Comment by wooorm** [comment]
Again, details has nothing to do with GFM or GitHub.

**Comment by kyeotic** [comment]
You guys keep saying that, but GitHub produces a collapsible. You can see it in the screenshot I posted above, or by looking at the README for [react-markdown](https://github.com/remarkjs/react-markdown). I don't know why you think those experiences on github.com have nothing to do with GitHub

**Comment by wooorm** [comment]
We’re saying it repeatedly because you seem to ignore it.
For an analogy, you’re saying that you see a book by a certain author and concluding from that that all books are by that author.

That is CommonMark. GitHub uses its own version of markdown, called GFM, which is a *superset* of CommonMark.

Here is how markdown works: https://spec.commonmark.org/dingus/?text=%3Cdetails%3E%0A%3Csummary%3ESome%20text%3C%2Fsummary%3E%0A%0AMore%20stuff%0A%0A%3C%2Fdetails%3E (please see the result, but also the AST tab).

You can read the CommonMark spec to figure out why this is the way it is. Why there are two HTML nodes.

React can’t deal with strings of HTML. That is a limitation imposed by React and why react-markdown can’t do the same as CommonMark/GFM by default.

The solution is complex and heavy: include an HTML parser. That’s why it’s not done by default.

**Comment by wooorm** [comment]
Note that GitHub itself makes the exact same decisions on how to handle HTML in markdown, include an HTML parser to parse things like details, and how to sanitize it (allowing details/summary but disallowing scripts).

**Comment by kyeotic** [comment]
> Here is how markdown works: https://spec.commonmark.org/dingus/?text=%3Cdetails%3E%0A%3Csummary%3ESome%20text%3C%2Fsummary%3E%0A%0AMore%20stuff%0A%0A%3C%2Fdetails%3E (please see the result, but also the AST tab).

Showing me that CommonMark behaves differently that GitHub only proves that this isn't part of CommonMark, which I have never argued. I don't expect this to work with CommonMark, I expect it to work with GFM. Here is how markdown [works on GitHub](https://github.com/remarkjs/react-markdown#use) (please see the collapsible).

> Note that GitHub itself makes the exact same decisions on how to handle HTML in markdown, include an HTML parser to parse things like details, and how to sanitize it (allowing details/summary but disallowing scripts).

Yes, this is exactly what I am saying. GitHub has chosen to give special behavior to a subset of HTML that includes `<details>`. That's the delta between GitHub (not CommonMark, GFM) and this package that is at issue.

> The solution is complex and heavy: include an HTML parser. That’s why it’s not done by default.

It's not done by this package, but it is done by GitHub. Note you don't need an general HTML parser, you only need to be able to parse two tags (details and summary), which do not support any attributes or other complexities that would make it harder than looking for the literal string `"<details>"` and `"</details>"`. This would be much lighter than `rehype-raw`

**Comment by wooorm** [comment]
Details is an html element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details.
It again does not receive special treatment from github. Hence my example, while showing the source instead of the rendered result, is exactly the same on github as on any commonmark supporting place.

**Comment by ChristianMurphy** [comment]
> Showing me that CommonMark behaves differently that GitHub only proves that this isn't part of CommonMark

He's showing the it behaves the same as GFM.

> GitHub has chosen to give special behavior to a subset of HTML that includes <details>. That's the delta between GitHub (not CommonMark, GFM) and this package that is at issue.

You're missing a key point here.
CommonMark, GFM, and most markdown flavors embed HTML.
HTML are different document(s), included inside the Markdown documents.

Markdown parsers will split the content into embeddings, here as a raw `html` node.
But how to handle the HTML itself is outside of what Markdown does.

For an anology, think for HTML and SVG, SVG documents can be put in HTML pages, but they aren't HTML.
The HTML sees something SVG like, and it hands off to the SVG engine to do the rest.

Here the same concept applies, Markdown sees something HTML like, and it can (optionally) hand it off to an HTML engine to do additional processing.

**Comment by kyeotic** [comment]
I think I understand the point you are trying to make. It still seems to me like a technical distinction that shouldn't be relevant, but that's because I'm focusing on the end result. This package isn't trying to match GitHub's result, its just trying to parse some markdown extensions that GitHub is adding to CommonMark.

I do appreciate you both taking the time to explain this from so many angles. Thank you. At least I learned something today :)

**Comment by ChristianMurphy** [comment]
> It still seems to me like a technical distinction that shouldn't be relevant

It usually isn't, in most cases plain text strings could be passed through just fine, but

> React can’t deal with strings of HTML. That is a limitation imposed by React and why `react-markdown` can’t do the same as CommonMark/GFM by default.

---

> its just trying to parse some markdown extensions that GFM is adding to CommonMark

Right
