### ISSUE TITLE
Nested bold, italics and strikethrough fails to parse on non-isolated words

### ISSUE THREAD

**Issue by rosskuyper** [remarkjs/remark-gfm#19]
### Subject of the issue

Nesting either bold, italics or both with strike-through does not work when the wrapped word(s) are not isolated.

i.e. `***~~Hello~~***Hello` should render with the first hello bolded, italicized and with strike-through, but it only renders the strike-through.

On github it renders correctly:

***~~Hello~~***Hello

If the word is isolated, i.e. `***~~Hello~~*** Hello`, then the styles are correctly applied. 

Nesting of bold and italics alone works correctly. 

### Your environment

*   **OS**: MacOS Big Sur 11.3.1
*   **Packages**: 
    "rehype-stringify": "8.0.0",
    "remark-gfm": "1.0.0",
    "remark-parse": "9.0.0",
    "remark-rehype": "8.1.0",
    "unified": "9.2.1"
*   **Env**: Node 14

### Steps to reproduce

https://codesandbox.io/s/agitated-mclaren-bynw8?file=/src/index.js

### Expected behavior

The nested word should have all styles applied.

### Actual behavior

Only strike-through is applied.

**Comment by wooorm** [comment]
Thanks for the repro!
The reason seams to be that, to CommonMark, whitespace before an attention run, and punctuation after, can’t form.

Take for example:

```markdown
***..This..***Doesn't
```

***..This..***Doesn't

GitHub changes how emphasis/strong work, too.

**Comment by wooorm** [comment]
I have confirmed that changing:

https://github.com/micromark/micromark/blob/4f92f355c8796555c8cd479ff94475e25b726b39/packages/micromark-util-classify-character/dev/index.js#L34

To:

```js
  if (unicodePunctuation(code) && code !== 126) {
```

Solves this. But now to find how to make this clean and configurable.

**Comment by rosskuyper** [comment]
Thanks, @wooorm. Anything I can do from my side to help with this?

**Comment by wooorm** [comment]
Solved through a patch to `micromark` and `micromark-extension-gfm-strikethrough`!
