### ISSUE TITLE
TypeError: self.parser.lazy is undefined

### ISSUE THREAD

**Issue by sunknudsen** [remarkjs/remark-gfm#21]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-gfm@2.0.0

### Steps to reproduce

Simplified snippet:

```tsx
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"

<ReactMarkdown
  children="# Foo\nbar\n"
  // @ts-expect-error # See https://github.com/rehypejs/rehype/discussions/63
  remarkPlugins={[remarkGfm]}
/>
```

Not sure why, but the `\n` characters appear to be throwing error.

### Expected behavior

No error

### Actual behavior

TypeError: self.parser.lazy is undefined
lineStart
node_modules/@sunknudsen/react-cms/node_modules/micromark-extension-gfm-table/lib/syntax.js:563

>  561 | 
>  562 |     function lineStart(code) {
>  563 |       return self.parser.lazy[self.now().line] ? nok(code) : ok(code)
>\> 564 |     }
>  565 |   }
>  566 | } // Based on micromark, but that won’t work as we’re in a table, and that expects
>  567 | // content.

### Runtime

Node v14

### Package manager

npm v6

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
the new version of this plugin uses an API not yet exposed in `remark-markdown`. A solution for now is to downgrade `remark-gfm` for a bit, and wait for `remark-markdown` to update!

**Comment by ChristianMurphy** [comment]
tracked upstream as https://github.com/remarkjs/react-markdown/issues/626

**Comment by sunknudsen** [comment]
Thanks for the heads-up guys!

**Comment by manunamz** [comment]
For posterity: Upgrading [`remark-parse`](https://github.com/remarkjs/remark/tree/main/packages/remark-parse) from `^9` to `^10` solved this issue for me.
