### ISSUE TITLE
Option for Autolinking Phone Numbers

### ISSUE THREAD

**Issue by steverecio** [remarkjs/remark-gfm#26]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

remark-gfm offers autolinking of URL literals (ie: https://xxx) but not phone numbers

### Solution

Add option to remark-gfm to autolink phone numbers in addition to URLs

### Alternatives

Because this project is focused on GitHub flavored markdown, perhaps this is better suited for a separate plugin ([discussion topic here](https://github.com/remarkjs/remark/discussions/890))

**Comment by Murderlon** [comment]
Hi, `remark-gfm` is not the place for this as it adheres to the [GitHub Flavored Markdown Spec](https://github.github.com/gfm/). Auto linking phone numbers is not part of GFM. If you want to create this yourself as a plugin, you could ask a [quality question](https://github.com/unifiedjs/.github/blob/main/support.md#asking-quality-questions) in your discussion.
