### ISSUE TITLE
New Feature: support for task lists inside tables

### ISSUE THREAD

**Issue by EvHaus** [remarkjs/remark-gfm#27]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

At the moment `remark-gfm` doesn't support task lists inside tables, but GitHub does. Try the following code in GitHub:

```
| Complete | Description | Units |
| --- | ----------- | --- |
| <ul><li>- [ ] </li></ul> | DB read I/O | int |
| <ul><li>- [ ] </li></ul> | DB write I/O | int |
| <ul><li>- [ ] </li></ul> | DB Read Latency | ms |
| <ul><li>- [ ] </li></ul> | DB Write Latency | ms |
| <ul><li>- [ ] </li></ul> | DB total transactions | int |
| <ul><li>- [ ] </li></ul> | DB total rows updated | int |
| <ul><li>- [ ] </li></ul> | DB total rows deleted | int |
| <ul><li>- [ ] </li></ul> | DB total rows inserted | int |
```

### Solution

Update `remark-gfm` so that `- []` values are converted into checkboxes even if they are inside table cells.

### Alternatives

Not sure

**Comment by wooorm** [comment]
What the heck?! How even?

```
| a |
| - |
| - [ ] |
| [ ] |
| <ul>- [ ]</ul> |
| <ul>[ ]</ul> |
| <ul><li>- [ ] </li></ul> |
| <ul><li>[ ] </li></ul> |
```

| a |
| - |
| - [ ] |
| [ ] |
| <ul>- [ ]</ul> |
| <ul>[ ]</ul> |
| <ul><li>- [ ] </li></ul> |
| <ul><li>[ ] </li></ul> |

The syntax doesn’t make sense in your example btw (`-` in a `li` would make it two?). Checked and it does work without the extra `-`, which then again is extremely weird that it’s dropped? 🤷‍♂️

I’d classify this as a bug with GH

**Comment by EvHaus** [comment]
Haha, true. That's GitHub being weird... What about supporting the last case in your example: `| <ul><li>[ ] </li></ul> |`? That seems pretty reasonable.

**Comment by wooorm** [comment]
- Seems bad to port (part) of an unspecified bug
- They do this on their platform, but not as part of GFM (markdown does not parse HTML, this needs context on which tags they do)
- as you’re injecting HTML, you can do `<ol><li><input type="checkbox"></li></ol>`?

**Comment by wooorm** [comment]
Closing as this is undocumented and really buggy behavior by them that is impossible to do by us on the markdown/micromark/remark level.
I’m open to including GHs undocumented behavior (much of their parsing is undocumented), and sometimes their bugs (e.g., links in links but not broken footnote matching), but the fact that this requires an HTML parser makes it a wontfix for me
