### ISSUE TITLE
id and anchor of footnote do not match with rehype-sanitize

### ISSUE THREAD

**Issue by UngkiH** [remarkjs/remark-gfm#28]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.1

### Steps to reproduce

``` js
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeSanitize from 'rehype-sanitize';

export type ViewerProps = {
  content: string;
};

const Viewer: FC<ViewerProps> = ({ content }: ViewerProps) => {
  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      rehypePlugins={[rehypeSanitize]}
    >
      {content}
    </ReactMarkdown>
  );
};
```

### Expected behavior

``` html
<a href="#user-content-fn1" id="user-content-fnref1"><sup>1</sup></a>

...

<li id="user-content-fn1">footnote...<a href="#user-content-fnref1">↩</a></li>
```

### Actual behavior

do not match with rehype-sanitize

``` html
<a href="#fn1" id="user-content-fnref1"><sup>1</sup></a>

...

<li id="user-content-fn1">footnote...<a href="#fnref1">↩</a></li>
```

Another result using rehype-react instead of react-markdown

`id="user-content-user-content-fnref-1"`

``` html
<a href="#user-content-fn-1" id="user-content-user-content-fnref-1" aria-describedby="footnote-label">1</a>

...

<li id="user-content-user-content-fn-1">
<p>footnote... <a href="#user-content-fnref-1" aria-label="Back to content">↩</a></p>
</li>
``` 

### Runtime

Node v14, Electron

### Package manager

yarn v1

### OS

macOS

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
https://github.com/rehypejs/rehype-sanitize#example-headings-dom-clobbering
