### ISSUE TITLE
Unable to escape GFM autolinking

### ISSUE THREAD

**Issue by tripodsan** [remarkjs/remark-gfm#33]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark@14.0.2, remark-parse@10.0.1, remark-gfm@3.0.1

### Link to runnable example

https://codesandbox.io/s/ecstatic-taussig-j1fxd

### Steps to reproduce

```js
const doc = `## test

https://www.example.com

https\\://www\\.example.com

`;
console.log('markdown:')
console.log(doc);

const mdast = unified()
  .use(remark)
  .use(gfm)
  .parse(doc);


console.log('mdast:')
console.log(inspect(mdast));

const md = unified()
  .use(stringify)
  .use(gfm)
  .stringify(mdast);

console.log('stringify md:')
console.log(md)
```

### Expected behavior

it should not create links for the escaped urls.

### Actual behavior

it creates links for the escaped urls:

```
root[3] (1:1-7:1, 0-61)
├─0 heading[1] (1:1-1:8, 0-7)
│   │ depth: 2
│   └─0 text "test" (1:4-1:8, 3-7)
├─1 paragraph[1] (3:1-3:24, 9-32)
│   └─0 link[1]
│       │ title: null
│       │ url: "https://www.example.com"
│       └─0 text "https://www.example.com"
└─2 paragraph[1] (5:1-5:26, 34-59)
    └─0 link[1]
        │ title: null
        │ url: "https://www.example.com"
        └─0 text "https://www.example.com"
```

Note, the escaped characters are already swallowed when parsing w/o gfm:

```
mdast:
root[3] (1:1-7:1, 0-61)
├─0 heading[1] (1:1-1:8, 0-7)
│   │ depth: 2
│   └─0 text "test" (1:4-1:8, 3-7)
├─1 paragraph[1] (3:1-3:24, 9-32)
│   └─0 text "https://www.example.com" (3:1-3:24, 9-32)
└─2 paragraph[1] (5:1-5:26, 34-59)
    └─0 text "https://www.example.com" (5:1-5:26, 34-59)
```

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

**Comment by wooorm** [comment]
This is expected. The same happens on GitHub (in files): https://gist.github.com/wooorm/76af9d43b37431f61d38327a40b47e11. (GH has bugs in all their implementations, we follow files as that seems most “canonical”)

**Comment by tripodsan** [comment]
> This is expected. The same happens on GitHub 

well, but highly unpractical. it used to be different for versions before the last major (esm) update. I assume the unescaping happens already in `mdast-from-markdown`, so it is almost impossible to for me to write a GFM plugin that respects the escaping.

do you have any recommendations how to tackle this problem?

**Comment by wooorm** [comment]
I believe we’ve had this conversation already: `remark-gfm` follows GFM. If you don’t want to follow GFM, don’t use `remark-gfm`. It used to be a bug. The bug is fixed.

> so it is almost impossible to for me to write a GFM plugin that respects the escaping.

Perhaps you should read the readmes of the the underlying tools:
- https://github.com/micromark/micromark-extension-gfm-autolink-literal
- https://github.com/syntax-tree/mdast-util-gfm-autolink-literal
I think they have the information you are looking for

---

Closing, because the current behavior matches GitHub
