### ISSUE TITLE
Footnotes in tables are listed in the wrong order

### ISSUE THREAD

**Issue by Josh-Cena** [remarkjs/remark-gfm#35]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

Tested with MDX v1/v2 playground + remark-gfm enabled

### Steps to reproduce

Consider this code:

```md
Before table[^t0]

| h1 [^h1] | h2 [^h2] | h3 [^h3] |
| --- | --- | --- |
| 1 [^c1] | 2 [^c2] | 3 [^c3] | 
| 4 [^c4] | 5 [^c5] | 6 [^c6] |
| 7 [^c7] | 8 [^c8] | 9 [^c9] |

After table[^t1]

[^t0]: t0
[^h1]: h1
[^h2]: h2
[^h3]: h3
[^c1]: c1
[^c2]: c2
[^c3]: c3
[^c4]: c4
[^c5]: c5
[^c6]: c6
[^c7]: c7
[^c8]: c8
[^c9]: c9
[^t1]: t1
```

This is tested in MDX [v1 playground](https://mdx-git-renovate-babel-monorepo-mdx.vercel.app/playground), [v2 playground](https://mdxjs.com/playground/), and Docusaurus which uses MDX v1. I've selected "other" in the environment because it's most easily reproduced in the playgrounds.

### Expected behavior

How GH renders it:

Before table[^t0]

| h1 [^h1] | h2 [^h2] | h3 [^h3] |
| --- | --- | --- |
| 1 [^c1] | 2 [^c2] | 3 [^c3] | 
| 4 [^c4] | 5 [^c5] | 6 [^c6] |
| 7 [^c7] | 8 [^c8] | 9 [^c9] |

After table[^t1]

[^t0]: t0
[^h1]: h1
[^h2]: h2
[^h3]: h3
[^c1]: c1
[^c2]: c2
[^c3]: c3
[^c4]: c4
[^c5]: c5
[^c6]: c6
[^c7]: c7
[^c8]: c8
[^c9]: c9
[^t1]: t1

### Actual behavior

In the MDX v2 playground (which I presume uses the latest versions of the dependencies):

1. t0
2. h3
3. h2
4. h1
5. c3
6. c2
7. c1
8. c6
9. c5
10. c4
11. c9
12. c8
13. c7
14. t1

p.s. this issue was first discovered in Docusaurus which uses MDX v1, which seems to include things like `remark-footnotes` by default. Interestingly, in v1 the footnotes are resolved in yet another order:

1. t0
2. c9
3. c8
4. c7
5. c6
6. c5
7. c4
8. c3
9. c2
10. c1
11. h3
12. h2
13. h1
14. t1

### Runtime

Node v17, Other (please specify in steps to reproduce)

### Package manager

yarn v1, Other (please specify in steps to reproduce)

### OS

macOS, Other (please specify in steps to reproduce)

### Build and bundle tools

Docusaurus, Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
Thanks for the report.
The “yet another method” you mention was solved in https://github.com/syntax-tree/mdast-util-to-hast/commit/fd38c45421bbec497f56e5c624eb8652d3a3bba4#diff-26dd410dc440b16482adff4a087672967680db3e7271052fbaab18a90a7d4ffe.

Here is a smaller reproduction:

```js
import {unified} from 'unified'
import remarkParse from 'remark-parse'
import remarkGfm from 'remark-gfm'
import remarkRehype from 'remark-rehype'
import rehypeStringify from 'rehype-stringify'

const file = await unified()
  .use(remarkParse)
  .use(remarkGfm)
  .use(remarkRehype)
  .use(rehypeStringify)
  .process(`| [^1] | [^2]
| --- | --- |
| [^3] | [^4]

[^1]: a
[^2]: b
[^3]: c
[^4]: d
`)

console.log(String(file));
```

Yields:

```html
<table>
<thead>
<tr>
<th><sup><a href="#user-content-fn-1" id="user-content-fnref-1" data-footnote-ref aria-describedby="footnote-label">2</a></sup></th>
<th><sup><a href="#user-content-fn-2" id="user-content-fnref-2" data-footnote-ref aria-describedby="footnote-label">1</a></sup></th>
</tr>
</thead>
<tbody>
<tr>
<td><sup><a href="#user-content-fn-3" id="user-content-fnref-3" data-footnote-ref aria-describedby="footnote-label">4</a></sup></td>
<td><sup><a href="#user-content-fn-4" id="user-content-fnref-4" data-footnote-ref aria-describedby="footnote-label">3</a></sup></td>
</tr>
</tbody>
</table>
<section data-footnotes class="footnotes"><h2 id="footnote-label" class="sr-only">Footnotes</h2>
<ol>
<li id="user-content-fn-2">
<p>b <a href="#user-content-fnref-2" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
<li id="user-content-fn-1">
<p>a <a href="#user-content-fnref-1" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
<li id="user-content-fn-4">
<p>d <a href="#user-content-fnref-4" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
<li id="user-content-fn-3">
<p>c <a href="#user-content-fnref-3" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
</ol>
</section>
```

**Comment by Josh-Cena** [comment]
Thanks a lot! It's a shame Docusaurus can't benefit from this any time soon though, since we are still CJS😄

**Comment by wooorm** [comment]
There are several ways to use ESM in CJS, and as a last resort you can always make a small vendored bundle with `npx esbuild ...`

**Comment by Josh-Cena** [comment]
Yeah, that's something we are exploring. Maybe we'll re-distribute MDX as a CJS bundle ourselves.
