### ISSUE TITLE
Table is not rendered properly 

### ISSUE THREAD

**Issue by young-trigold** [remarkjs/remark-gfm#37]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-gfm v3.0.1

### Steps to reproduce

Following is a table markdown content, but remark-gfm can't render it properly:

| 模式                                 | 代表元素                                                                         | 描述                                                                           | 级别       |
| ------------------------------------ | -------------------------------------------------------------------------------- | ------------------------------------------------------------------------------ | ---------- | --- |
| `\*`                                 | 任何元素                                                                         | 通用选择器                                                                     | 2          |
| `E`                                  | 一个 E 类型的元素                                                                | 类型选择器                                                                     | 1          |
| `E[foo]`                             | 一个具有 "foo" 属性的 E 元素                                                     | 属性选择器                                                                     | 2          |
| `E[foo="bar"]`                       | 一个 E 元素，其 "foo" 属性值正好等于 "bar"                                       | 属性选择器                                                                     | 2          |
| `E[foo~="bar"]`                      | 一个 E 元素，其 "foo" 属性值是一个以空白分隔的值，其中一个正好等于 "bar"         | 属性选择器                                                                     | 2          |
| `E[foo^="bar"]`                      | 一个 E 元素，它的 "foo" 属性值正好以字符串 "bar" 开始                            | 属性选择器                                                                     | 3          |
| `E[foo$="bar"]`                      | 一个 E 元素，其 "foo" 属性值正好以字符串 "bar" 结束                              | 属性选择器                                                                     | 3          |
| `E[foo*="bar"]`                      | 一个 E 元素，其 "foo" 属性值包含子串 "bar"                                       | 属性选择器                                                                     | 3          |
| `E[foo                               | ="en"]`                                                                          | 一个 E 元素，其 "foo" 属性有一个以 "en" 开头的连字符分隔的值列表（从左边开始） | 属性选择器 | 2   |
| `E:root`                             | 一个 E 元素，文档的根结构                                                        | 伪类                                                                           | 3          |
| `E:nth-child(n)`                     | 一个 E 元素，是其父元素的第 n 个子元素                                           | 结构性伪类                                                                     | 3          |
| `E:nth-last-child(n)`                | 一个 E 元素，是其父元素的第 n 个子元素，从最后一个开始计算                       | 结构性伪类                                                                     | 3          |
| `E:nth-of-type(n)`                   | 一个 E 元素，是其类型的第 n 个兄弟元素                                           | 结构性伪类                                                                     | 3          |
| `E:nth-last-of-type(n)`              | 一个 E 元素，它的类型的第 n 个兄弟元素，从最后一个开始计算                       | 结构性伪类                                                                     | 3          |
| `E:first-child`                      | 一个 E 元素，是其父元素的第一个子元素                                            | 结构性伪类                                                                     | 2          |
| `E:last-child`                       | 一个 E 元素，是其父元素的最后一个子元素                                          | 结构性伪类                                                                     | 3          |
| `E:first-of-type`                    | 一个 E 元素，其类型的第一个兄弟元素                                              | 结构化伪类                                                                     | 3          |
| `E:last-of-type`                     | 一个 E 元素，其类型的最后一个兄弟元素                                            | 结构性伪类                                                                     | 3          |
| `E:only-child`                       | 一个 E 元素，是其父元素的唯一子元素                                              | 结构性伪类                                                                     | 3          |
| `E:only-of-type`                     | 一个 E 元素，是其类型的唯一兄弟元素                                              | 结构性伪类                                                                     | 3          |
| `E:empty`                            | 一个 E 元素，没有子节点（包括文本节点）                                          | 结构性伪类                                                                     | 3          |
| `E:link 和 E:visited`                | 一个 E 元素是一个超链接的锚点，其目标尚未被访问（:link）或已经被访问（:visited） | 链接伪类                                                                       | 1          |
| `E:active` 和 `E:hover` 和 `E:focus` | 在某些用户操作期间的一个 E 元素                                                  | 用户操作伪类                                                                   | 1 和 2     |
| `E:target`                           | 一个 E 元素，是引用 URI 的目标                                                   | target 伪类                                                                    | 3          |
| `E:lang(fr)`                         | 一个语言为 "fr" 的 E 类型元素（文件语言指定如何确定语言）                        | :lang 伪类                                                                     | 2          |
| `E:enabled` 和 `E:disabled`          | 一个用户界面元素 E，它被启用或禁用                                               | UI 元素状态伪类                                                                | 3          |
| `E:checked`                          | 一个被选中的用户界面元素 E（例如一个单选按钮或复选框）                           | UI 元素说明伪类                                                                | 3          |
| `E::first-line`                      | 一个 E 元素的第一个格式化行                                                      | ::first-line 伪元素                                                            | 1          |
| `E::first-letter`                    | 一个 E 元素的第一个格式化的字母                                                  | ::first-letter 伪元素                                                          | 1          |
| `E::before`                          | 在 E 元素之前生成的内容                                                          | ::before 伪元素                                                                | 2          |
| `E::after`                           | 在一个 E 元素之后生成的内容                                                      | ::after 伪元素                                                                 | 2          |
| `E.warning`                          | 一个 E 元素，它的类是 "warning"（文档语言指定类是如何确定的）                    | 类选择器                                                                       | 1          |
| `E#myid`                             | 一个 E 元素，ID 等于 "myid"                                                      | ID 选择器                                                                      | 1          |
| `E:not(s)`                           | 一个 E 元素，不符合简单选择器 s                                                  | 否定伪类                                                                       | 3          |
| `E F`                                | 一个 E 元素的 F 元素的后代元素                                                   | 后代元素组合符                                                                 | 1          |
| `E > F`                              | 一个 E 元素的 F 元素的子元素                                                     | 子元素组合符                                                                   | 2          |
| `E + F`                              | 一个 F 元素紧挨着一个 E 元素的后置元素                                           | 下一个下一个兄弟元素组合符                                                     | 2          |
| `E ~ F`                              | 一个 F 元素前面有一个 E 元素                                                     | 后续兄弟元素组合符                                                             | 3          |

### Expected behavior

Following is same table markdown content rendered in Markdown previewed enhanced.

<img width="502" alt="image" src="https://user-images.githubusercontent.com/56287461/152300346-e23d9d8d-e839-4f36-9430-f53c301d100c.png">

### Actual behavior

I use react markdown with remark-gfm in my blog project (http://www.trigold.tech/reading/chapters/61fb832c8d6e8a5f5120d110) to render the table markdown content.

Following is the code:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/56287461/152299434-7e3c1619-9af7-4019-9a5c-6153d08f0e2d.png">

But I got this:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/56287461/152299557-f6b7b947-7821-45da-948e-201b46ca0b9f.png">

### Package manager

npm

### OS

windows 11 21H2, Chrome v97.0.4692.99

### Build and bundle tools

create-react-app

**Comment by wooorm** [comment]
The table doesn’t render on GitHub either, so it seems that `remark-gfm` following GFM, and that this isn’t an issue
