### ISSUE TITLE
Add option to control `Footnotes` label

### ISSUE THREAD

**Issue by ahmedelq** [remarkjs/remark-gfm#38]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

After generating the html I end up with an unwanted `Footnotes` label.
This doesn't support i18n, add an option to either change or turn this label off. 

```
<h2>Footnotes (👈  add an option to change this)</h2>
<ol><li id="user-content-fn-1">
<p>This is a note<a class="data-footnote-backref" href="#user-content-fnref-1" data-footnote-backref="true" aria-label="Back to content">↩</a></p>
</li></ol>
```

### Solution

Add support for the `micromark-extension-gfm`'s options:  `label`, `backLabel`, and `clobberPrefix`

### Alternatives

N/A

**Comment by wooorm** [comment]
This is mentioned in the readme:

> This plugin does not handle how markdown is turned to HTML. That’s done by [remark-rehype](https://github.com/remarkjs/remark-rehype). If your content is not in English and uses footnotes, you should configure that plugin.

More there: https://github.com/remarkjs/remark-rehype#example-footnotes-in-languages-other-than-english

**Comment by CyanoFresh** [comment]
just for visibility, working example with react-markdown:
```jsx
<Markdown
  remarkPlugins={[remarkGfm]}
  remarkRehypeOptions={{
    footnoteLabel: 'Sources',
  }}
...
```
