### ISSUE TITLE
Link text are getting escaped like this http\://localhost

### ISSUE THREAD

**Issue by marcofranssen** [remarkjs/remark-gfm#4]
### Subject of the issue

Following markdown gets replaced with an escaped link text.

```md
[http://localhost]: http://localhost "Your localhost webserver running on http"

# My document title

This is my input markdown using a link reference [http://localhost][].
```

Which in turn is translated to 

```md
[http://localhost]: http://localhost "Your localhost webserver running on http"

# My document title

This is my input markdown using a link reference [http\://localhost][http://localhost].
```

### Your environment

*   **OS**: MacOS
*   **Packages**: remark 13.0.0, remark-gfm 1.0.0
*   **Env**: node 15.0.3

### Steps to reproduce

https://codesandbox.io/s/remark-debug-forked-ocyxp?file=/src/index.js

### Expected behavior

The result should be like

```md
[http://localhost]: http://localhost "Your localhost webserver running on http"

# My document title

This is my input markdown using a link reference [http://localhost][http://localhost] and some more text.
```

### Actual behavior

```md
[http://localhost]: http://localhost "Your localhost webserver running on http"

# My document title

This is my input markdown using a link reference [http\://localhost][http://localhost] and some more text.
```

**Comment by wooorm** [comment]
I guess it’s not needed in that case. A PR to add [`label`](https://github.com/syntax-tree/mdast-util-to-markdown/blob/e951290cc49e1a3849321073aa2dde19607d54ac/lib/handle/link-reference.js#L11) here: https://github.com/syntax-tree/mdast-util-gfm-autolink-literal/blob/109db3c32cd54f517e71c03b54f097e26fdf12cc/to-markdown.js#L2 would be appreciated!

**Comment by marcofranssen** [comment]
@wooorm you mean that array only would need `label` to resolve the issue?

**Comment by wooorm** [comment]
Think so!

Would need some tests.

And there are other (related) things that use 'label', which might be good to check.

But generally, when a url is in a link (or image) label, I guess it doesn't need to be escaped, because the surrounding link is well, already a link

**Comment by wooorm** [comment]
Released! https://github.com/syntax-tree/mdast-util-gfm-autolink-literal/releases/tag/0.1.2
