### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by nuvacore** [remarkjs/remark-gfm#43]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Github supports Mermaid, gfm does not.

### Solution

Can you add support for Mermaid?

### Alternatives

?

**Comment by ChristianMurphy** [comment]
> Github supports Mermaid, gfm does not.

That is the crux of the problem.
GitHub.com and GFM (both by GitHub) are different, and have been diverging for a while.
GFM the standard maintained by GitHub does not include Mermaid.
https://github.github.com/gfm/

---

https://github.com/orgs/remarkjs/discussions/932
Has some discussion on offering some mermaid support through a separate plugin.
And some candidates that you could try today

**Comment by remcohaszing** [comment]
In addition to @ChristianMurphy's comment, I'd like to add that `remark-gfm` adds support for syntax. Mermaid support is different, it needs to transform the AST.

Also Mermaid doesn't work in Node.js. If `remark-gfm` added support, it would require some heavy dependencies like Mermaid and Puppeteer.

**Comment by wooorm** [comment]
This is out of scope for this package. This package focusses on GFM. Which is the parsing side in markdown. Supporting mermaid is something that GH does which is not part of GFM. And is solved in the HTML postprocessing stages.
