### ISSUE TITLE
Footnotes and Checklists not working with string from server

### ISSUE THREAD

**Issue by hahnbeelee** [remarkjs/remark-gfm#44]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

^3.0.1

### Link to runnable example

[Code sandbox](https://codesandbox.io/p/sandbox/tender-mountain-hi19rk?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A8%2C%22endLineNumber%22%3A32%2C%22startColumn%22%3A8%2C%22startLineNumber%22%3A32%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8skx9ay000hlpge4cua49bz%2522%252C%2522openFiles%2522%253A%255B%2522%252Fpackage.json%2522%252C%2522%252Fpages%252Findex.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522claugm1xs01hk3b6lv1idf122%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

### Steps to reproduce

I recently migrated my next.js app from reading directly from mdx files to using hashicorp's next-mdx-remote. Since then my content has been coming from my backend. And since then footnotes and checklists have been broken. I suspect this has to do with how javascript formats a string when sending it.

For example: This string works as desired when i use it directly
```
`- [x] You can also help us with documentation and tutorials. Here is how you can
      contribute by writing

- [x] Share with your friends and spread the word.`
```

However when I send it through a server it becomes like this:
```
"*   \\[x] You can also help us with documentation and tutorials. Here is how you can\n    contribute by writing\n    [documentation](https://docs.mindsdb.com/contribute/docs/) and\n    [tutorials](https://docs.mindsdb.com/sql/tutorials/home-rentals/). Don't\n    forget to follow the [style guide](https://docs.mindsdb.com/docs-rules/).\n\n*   \\[x] Share with your friends and spread the word about MindsDB.
```

I've tried a hack approach of `content.replace(/\*   \\\\\[x]/g, "*   [x]")` but this isn't working for me.

### Expected behavior

A checkbox:
<img width="70" alt="image" src="https://user-images.githubusercontent.com/55263191/203733902-a566a5c5-bde1-46b7-8fa1-a79dae60ecb6.png">

### Actual behavior

Checkbox does not get rendered:
<img width="78" alt="image" src="https://user-images.githubusercontent.com/55263191/203734142-62e78fc3-b6f7-4055-a783-4d5dd31a649b.png">

### Runtime

Node v17

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Next.js

**Comment by wooorm** [comment]
> Since then my content has been coming from my backend

Which backend?

> And since then footnotes and checklists have been broken.

Well, then you are not using this plugin in some place. Or the place where you use it, doesn’t understand this plugin.

**Comment by hahnbeelee** [comment]
Ah gotcha, I assumed it was a fault of the plugin with detecting syntax because only footnotes and checklists weren't working, but that makes a lot of sense. There's definitely something happening in my backend that is misconstruing the strings.

**Comment by hahnbeelee** [comment]
@wooorm I figured it out. I parse my content once through remark on the server (I edit my content twice, once in the backend and once in next.js because I want a separation between UI changes vs. content changes (e.g. Change image urls to hosted images on s3)) Turns out if you feed content with gfm in it without adding the remark plugin it escapes it. Not sure if this is intentional, but this was kind of unexpected behavior for me. Here's [an example](https://codesandbox.io/s/remove-imports-forked-z5m1sb?file=/src/index.js).

**Comment by wooorm** [comment]
> Not sure if this is intentional

Yes. It is intentional. You need to specify what custom flavor of markdown you are using. In all places that deal with markdown. Otherwise it is assumed you are using CommonMark (standard markdown).
