### ISSUE TITLE
Table with long cell contents not properly rendered (we should not pad forever)

### ISSUE THREAD

**Issue by nikku** [remarkjs/remark-gfm#46]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-gfm

### Link to runnable example

https://codesandbox.io/s/quiet-shape-cinj8j?file=/src/index.js

### Steps to reproduce

Create a table with longer cell contents:

```markdown
| A table | With another Column |
| :--- | ---: |
| Some | Content |
| Some | Super long cell content, can we handle it? or will it break? yes, multi-line just works, too? |
```

Pipe it through `remark -> remark-gfm -> remark-stringify`.

### Expected behavior

After stringification the markdown remains readable.

### Actual behavior

See that table is rendered unreadable (normal padding takes place):

```markdown
| A table |                                                                           With another Column |
| :------ | --------------------------------------------------------------------------------------------: |
| Some    |                                                                                       Content |
| Some    | Super long cell content, can we handle it? or will it break? yes, multi-line just works, too? |
```

### Runtime

Node v16

### Package manager

npm 8

### OS

Linux

### Build and bundle tools

Other (please specify in steps to reproduce)

**Comment by wooorm** [comment]
What isn’t proper about it? Seems most people want aligned cells. But if you don’t, turn it off: https://github.com/remarkjs/remark-gfm#optionstablepipealign

**Comment by nikku** [comment]
Thanks for the quick response. 

Thinking about it there seems to be no better way than scrolling forever in tables with large cells. Everything else, i.e. an adaptive mode, will make things worse, rather than better. I thought initially that we could stop padding after a certain cell width, but how would that help?

Closing this issue.

**Comment by wooorm** [comment]
Perhaps one way to go about it is to set a threshold, either per column, or for the whole table. Either for max number of padding (e.g., 30 spaces is too much: stagger the table instead of aligning it), or for the max size of a cell/table (e.g., 100 chars is too much).

**Comment by nikku** [comment]
> What type of adaptive mode are you thinking off?

Exactly what you describe, i.e. not account for _huge_ contents in column width computation. However that would break follow up padding (for these columns only).

The benefit though would be that if only a few colums are huge then the actual table would not be overall broken:


```
| A    | B    | C    |
| :--- | :--- | :--- |
| aaaa | bcaa | asdd |
| a    |    1 | asdd |
| a    |    2 | asdd |
| a    |    3 | SUPER LONG AND HUGE CELL; WELL SIMPLY NOT ACCOUNT FOR IT DURING COLUMN WIDTH COMPUTATION |
| a    |    SUPER LONG AND HUGE CELL; WELL SIMPLY NOT ACCOUNT FOR IT DURING COLUMN WIDTH COMPUTATION | asdd |
| a    |    4 | asdd |
| a    |    4 | asdd |
| a    |    4 | asdd |
| a    |    4 | asdd |
```

I've tried to use `stringWidth = (s) => s.length > 100 ? -1 : s.length`, but that did not do the job.

**Comment by nikku** [comment]
> Ah, you seem to show that this threshold only applies to certain cells in rows. I was thinking of applying to the entire table

I think per column threshoulds would yield more meainingful results. The alternative is this:

```markdown
| A | B | C |
| :--- | :--- | :--- |
| aaaa | bcaa | asdd |
| a | 1 | asdd |
| a | 2 | asdd |
| a | 3 | SUPER LONG LONG LONG LONG AND HUGE CELL; WELL SIMPLY NOT ACCOUNT FOR IT DURING COLUMN WIDTH COMPUTATION |
| a | SUPER LONG LONG LONG LONG AND HUGE CELL; WELL SIMPLY NOT ACCOUNT FOR IT DURING COLUMN WIDTH COMPUTATION | asdd |
| a | 4 | asdd |
| a | 4 | asdd |
| a | 4 | asdd |
| a | 4 | asdd |
```

**Comment by wooorm** [comment]
I don’t mind that result. There are currently two ways to display tables. I can see “dynamically” switching between them as an improvement. Instead of adding a new, third, style (your [earlier comment](https://github.com/remarkjs/remark-gfm/issues/46#issuecomment-1375918407)).

**Comment by nikku** [comment]
Both would solve my use-case, I have a slight personal preference for https://github.com/remarkjs/remark-gfm/issues/46#issuecomment-1375918407, which may be harder to get right.

**Comment by wooorm** [comment]
Okay, well. If you’re interested in working on it, and there’s an acceptable solution for either algorithm, I’d probably be open to have it in [`markdown-table`](https://github.com/wooorm/markdown-table)!

I don’t care strongly about this though, so I’m not interested in working on it currently myself!
