### ISSUE TITLE
Footnotes order inside table is reversed

### ISSUE THREAD

**Issue by magicpalmtree** [remarkjs/remark-gfm#49]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"remark-gfm": "^3.0.1" 

### Steps to reproduce

// Node v18.13.0

```
/* Input */
Before tableeeeeeeeeee [^t0]

| h1 [^h1] | h2 [^h2] | h3 [^h3] |
| --- | --- | --- |
| 1 [^c1] | 2 [^c2] | 3 [^c3] | 
| 4 [^c4] | 5 [^c5] | 6 [^c6] |
| 7 [^c7] | 8 [^c8] | 9 [^c9] |

After table[^t1]

[^t0]: t0
[^h1]: h1
[^h2]: h2
[^h3]: h3
[^c8]: c8
[^c9]: c9
[^t1]: t1
[^c1]: c1
[^c2]: c2
[^c3]: c3
[^c4]: c4
[^c5]: c5
[^c6]: c6
[^c7]: c7
```
```
/* mdsvex.config.js */
const config = defineConfig({
	extensions: ['.svelte.md', '.md', '.svx'],

	remarkPlugins: [
		remarkParse,
		remarkGfm,
	],
	rehypePlugins: [
		rehypeStringify,
	 ],
	... More Code ...
});

```
```
/* svelte.config.js */
... More Code ...
import { mdsvex } from 'mdsvex';
import mdsvexConfig from './mdsvex.config.js';

const config = {
	extensions: ['.svelte', ...mdsvexConfig.extensions],

	preprocess: [
		mdsvex(mdsvexConfig)
	],
	... More Code ...
}
```

### Expected behavior

<p style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin-block: 0px calc(1em + 1ex); color: rgb(240, 246, 252); font-family: system-ui, -apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, helvetica, arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 18px; font-variant-ligatures: normal; orphans: 2; widows: 2; text-decoration-thickness: initial;">Before tableeeeeeeeeee<span> </span><sup style="box-sizing: border-box; vertical-align: top;"><a href="https://mdxjs.com/playground/#user-content-fn-t0" id="user-content-fnref-t0" data-footnote-ref="true" aria-describedby="footnote-label" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">1</a></sup></p>

h1 2 | h2 3 | h3 4
-- | -- | --
1 5 | 2 6 | 3 7
4 8 | 5 9 | 6 10
7 11 | 8 12 | 9 13

<p style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; margin-block: calc(1em + 1ex); color: rgb(240, 246, 252); font-family: system-ui, -apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, helvetica, arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 18px; font-variant-ligatures: normal; orphans: 2; widows: 2; text-decoration-thickness: initial;">After table<sup style="box-sizing: border-box; vertical-align: top;"><a href="https://mdxjs.com/playground/#user-content-fn-t1" id="user-content-fnref-t1" data-footnote-ref="true" aria-describedby="footnote-label" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">14</a></sup></p><section data-footnotes="true" class="footnotes" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; color: rgb(240, 246, 252); font-family: system-ui, -apple-system, blinkmacsystemfont, &quot;Segoe UI&quot;, helvetica, arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 18px; font-variant-ligatures: normal; orphans: 2; widows: 2; text-decoration-thickness: initial;"><h2 class="sr-only" id="footnote-label" style="box-sizing: border-box; font-weight: 700; letter-spacing: 0.0125em; margin-block: calc(0.4em + 0.4ex); display: block; scroll-margin-block-start: 6rem; font-size: 2.5em; line-height: calc(1em + 0.4ex);">Footnotes</h2><ol style="box-sizing: border-box; margin-block: calc(1em + 1ex); padding-inline-start: 0px; list-style-type: decimal;"><li id="user-content-fn-t0" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">t0<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-t0" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-h1" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">h1<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-h1" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-h2" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">h2<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-h2" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-h3" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">h3<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-h3" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-c1" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">c1<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-c1" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-c2" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">c2<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-c2" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-c3" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">c3<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-c3" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-c4" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">c4<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-c4" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-c5" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">c5<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-c5" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-c6" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">c6<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-c6" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-c7" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">c7<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-c7" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-c8" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">c8<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-c8" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-c9" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">c9<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-c9" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li><li id="user-content-fn-t1" style="box-sizing: border-box; margin-block: calc(0.25em + 0.25ex); margin-inline-start: calc(1em + 1ex);"><p style="box-sizing: border-box; margin-block: calc(1em + 1ex);">t1<span> </span><a href="https://mdxjs.com/playground/#user-content-fnref-t1" data-footnote-backref="true" class="data-footnote-backref" aria-label="Back to content" style="box-sizing: border-box; color: var(--hl); transition: color 0.2s ease 0s;">↩</a></p></li></ol></section>

### Actual behavior

<p class="these custom components dont frigging work" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-family: Iosevka, monospace; color: rgba(0, 0, 0, 0.933); font-size: medium; font-variant-ligatures: normal; orphans: 2; widows: 2; background-color: rgb(255, 255, 255); text-decoration-thickness: initial;">Before tableeeeeeeeeee<span> </span><sup id="fnref-t0"><a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fn-t0" class="footnote-ref" style="font-family: Iosevka, monospace; color: var(--text-primary);">t0</a></sup></p>

h1 h1 | h2 h2 | h3 h3
-- | -- | --
1 c1 | 2 c2 | 3 c3
4 c4 | 5 c5 | 6 c6
7 c7 | 8 c8 | 9 c9

<p class="these custom components dont frigging work" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-family: Iosevka, monospace; color: rgba(0, 0, 0, 0.933); font-size: medium; font-variant-ligatures: normal; orphans: 2; widows: 2; background-color: rgb(255, 255, 255); text-decoration-thickness: initial;">After table<sup id="fnref-t1"><a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fn-t1" class="footnote-ref" style="font-family: Iosevka, monospace; color: var(--text-primary);">t1</a></sup></p><div class="footnotes" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-family: Iosevka, monospace; color: rgba(0, 0, 0, 0.933); font-size: medium; font-variant-ligatures: normal; orphans: 2; widows: 2; background-color: rgb(255, 255, 255); text-decoration-thickness: initial;"><hr><ol><li id="fn-t0">t0<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-t0" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-c9">c9<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-c9" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-c8">c8<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-c8" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-c7">c7<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-c7" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-c6">c6<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-c6" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-c5">c5<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-c5" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-c4">c4<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-c4" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-c3">c3<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-c3" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-c2">c2<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-c2" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-c1">c1<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-c1" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-h3">h3<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-h3" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-h2">h2<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-h2" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-h1">h1<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-h1" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li><li id="fn-t1">t1<a href="http://localhost:5173/daolabs/daos/move/proposals/README.md#fnref-t1" class="footnote-backref" style="font-family: Iosevka, monospace; color: var(--text-primary);">↩</a></li></ol></div>

The point is that the footnote order inside table is reversed :/

### Runtime

Other (please specify in steps to reproduce)

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Vite

**Comment by wooorm** [comment]
This was solved a year ago: https://github.com/syntax-tree/mdast-util-to-hast/releases/tag/12.1.1

**Comment by magicpalmtree** [comment]
> This was solved a year ago: https://github.com/syntax-tree/mdast-util-to-hast/releases/tag/12.1.1

did you checked with svelte+vite+mdsvex?

**Comment by wooorm** [comment]
Why should I check those tools? I don’t work on them. If it’s an issue there, raise it there

**Comment by magicpalmtree** [comment]
> Why should I check those tools? I don’t work on them. If it’s an issue there, raise it there

the issue is just on remark-gfm itself. actually other remark- packages are all working fine

**Comment by wooorm** [comment]
No it’s not, `remark-gfm` doesn’t handle how tables are turned into HTML. That’s what `remark-rehype`/`mdast-util-to-hast` do. It’s fixed there.
All remark packages are working fine. The problem is in your other tools.

**Comment by magicpalmtree** [comment]
![Screen Shot 2023-02-08 at 5 28 18 AM](https://user-images.githubusercontent.com/3953388/217504245-e37009cd-f914-450b-a733-fe4b286f8a78.png)

**Comment by wooorm** [comment]
What?

**Comment by magicpalmtree** [comment]
actually there is no problem with table.
markdown is converted perfectly with just `remark-parse` and `remark-gfm`.
but the issue is just on footnotes inside table.

if I remove remark-gfm and just use remark-rehype & remark-footnotes, then the footnotes order is fine but the table is not converted. the only way I can see table is using remark-gfm, but if I use that, footnotes order breaks.

**Comment by wooorm** [comment]
Codesandbox has some caching issues. Try on your computer:

```js
import {unified} from 'unified'
import remarkParse from 'remark-parse'
import remarkGfm from 'remark-gfm'
import remarkRehype from './index.js'
import remarkStringify from 'rehype-stringify'

const file = await unified()
  .use(remarkParse)
  .use(remarkGfm)
  .use(remarkRehype)
  .use(remarkStringify)
  .process(
    `Before tableeeeeeeeeee [^t0]

| h1 [^h1] | h2 [^h2] |
| --- | --- |
| 1 [^c1] | 2 [^c2] |

After table[^t1]

[^t0]: t0
[^h1]: h1
[^h2]: h2
[^t1]: t1
[^c1]: c1
[^c2]: c2
`
  )

console.log(String(file))
```

```html
<p>Before tableeeeeeeeeee <sup><a href="#user-content-fn-t0" id="user-content-fnref-t0" data-footnote-ref aria-describedby="footnote-label">1</a></sup></p>
<table>
<thead>
<tr>
<th>h1 <sup><a href="#user-content-fn-h1" id="user-content-fnref-h1" data-footnote-ref aria-describedby="footnote-label">2</a></sup></th>
<th>h2 <sup><a href="#user-content-fn-h2" id="user-content-fnref-h2" data-footnote-ref aria-describedby="footnote-label">3</a></sup></th>
</tr>
</thead>
<tbody>
<tr>
<td>1 <sup><a href="#user-content-fn-c1" id="user-content-fnref-c1" data-footnote-ref aria-describedby="footnote-label">4</a></sup></td>
<td>2 <sup><a href="#user-content-fn-c2" id="user-content-fnref-c2" data-footnote-ref aria-describedby="footnote-label">5</a></sup></td>
</tr>
</tbody>
</table>
<p>After table<sup><a href="#user-content-fn-t1" id="user-content-fnref-t1" data-footnote-ref aria-describedby="footnote-label">6</a></sup></p>
<section data-footnotes class="footnotes"><h2 class="sr-only" id="footnote-label">Footnotes</h2>
<ol>
<li id="user-content-fn-t0">
<p>t0 <a href="#user-content-fnref-t0" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
<li id="user-content-fn-h1">
<p>h1 <a href="#user-content-fnref-h1" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
<li id="user-content-fn-h2">
<p>h2 <a href="#user-content-fnref-h2" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
<li id="user-content-fn-c1">
<p>c1 <a href="#user-content-fnref-c1" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
<li id="user-content-fn-c2">
<p>c2 <a href="#user-content-fnref-c2" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
<li id="user-content-fn-t1">
<p>t1 <a href="#user-content-fnref-t1" data-footnote-backref class="data-footnote-backref" aria-label="Back to content">↩</a></p>
</li>
</ol>
</section>
```

---

I gave you the solution three times: it’s not here, it’s in your other tools.

**Comment by magicpalmtree** [comment]
Yeah, it's working on local.
seems the issue is on other part.
Thanks.  👍
