### ISSUE TITLE
Header information not parsed for example table

### ISSUE THREAD

**Issue by cco3** [remarkjs/remark-gfm#5]
https://astexplorer.net/#/gist/0a92bbf654aca4fdfb3f139254cf0bad/a1cde03a6021091b767d1771fcbdbcc2b93431a0

I'd expect the cells above the dividing line to be marked as th elements in someway, but I see nothing here.

**Comment by ChristianMurphy** [comment]
This is noted in the [mdast spec](https://github.com/syntax-tree/mdast):

https://github.com/syntax-tree/mdast#tablecell

> `TableCell` (`Parent`) represents a header cell in a `Table`, if its parent is a `head`, or a data cell otherwise.

and the reference for `head`

> *Head*
>
> The head of a node is its first child (if any).
