### ISSUE TITLE
Footnote doesn't seem working

### ISSUE THREAD

**Issue by jkim34** [remarkjs/remark-gfm#50]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

"remark-gfm": "^3.0.1"

### Steps to reproduce

Try accessing codesandbox: https://codesandbox.io/s/silent-smoke-8l4m7p?file=/src/app.tsx
- from sandbox, comment out footnote to remove errors, from `app.tsx`

Or,

Using npm 9.2.0
1. Install "remark-gfm": "^3.0.1"
2. Try adding footnote, such as one below (which is straight from the sample):
```
## Footnote

A note[^1]

[^1]: Big note.
```

### Expected behavior

Should display footnote.

### Actual behavior

- Error from codesandbox, and
- Unexpected CSS behavior from my react local environment when embedded within React container, as shown below:
![image](https://github.com/remarkjs/remark-gfm/assets/27513386/d32508c8-b41d-4b8f-9cd9-66c4ed17fb08)

### Runtime

Node v14

### Package manager

Other (please specify in steps to reproduce)

### OS

Windows

### Build and bundle tools

Create React App

**Comment by wooorm** [comment]
Hi!

The stackblitz error is a stackblitz error, it sometimes has problems resolving dependencies. In the [`react-markdown` tests](https://github.com/remarkjs/react-markdown/blob/d044e34b4f22caa24545c0b355d2205de42dfc32/test/test.jsx#L880-L897), you can see that they work fine.

As for CSS: there is no bug. There’s just your style presenting things as such. You can use different CSS to make it look the way you want. How to use CSS in React is outside of the scope of this project though.

**Comment by zhxlp** [comment]
示范点发射点发[1][2]

[1]: [xxxxx](#xx)
[2]: [bbbb](#bb)
