### ISSUE TITLE
Performance issues with large data.

### ISSUE THREAD

**Issue by cuongnm63** [remarkjs/remark-gfm#51]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.1

### Steps to reproduce

I'm using ReactMarkdown and included **remarkGfm** as **remarkPlugins**.
This is the markdown content i'm using.
[markdown.txt](https://github.com/remarkjs/remark-gfm/files/11598369/markdown.txt)

### Expected behavior

It's should not causing any lagging.

### Actual behavior

It's causing lagging and in mobile device it's cannot load.

### Runtime

Node v16

### Package manager

npm 8

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
Duplicate of #45
