### ISSUE TITLE
Is there a plan switch micromark-extension-gfm to markdown-rs

### ISSUE THREAD

**Issue by linzhefeng** [remarkjs/remark-gfm#52]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

I have the same performance issue as #48 , I got a suggestion that I could switch to a rust version, but I don't know rust well;
Is there has a plan to do this, or any sugestion

### Solution

I need high performance gfm

### Alternatives

-

**Comment by wooorm** [comment]
No. This is more of a discussion. And this project is a particular remark plugin, so that’s not going to happen here.

> I have the same performance issue as https://github.com/remarkjs/remark-gfm/issues/48

That’s already fixed. Remove `node_modules` and run `npm install`.

**Comment by linzhefeng** [comment]
thx, btw which version this issue was fixed from?

**Comment by wooorm** [comment]
https://github.com/micromark/micromark-extension-gfm-table/releases/tag/1.0.6
