### ISSUE TITLE
Support GitHub's note/warning/information alerts?

### ISSUE THREAD

**Issue by Elchi3** [remarkjs/remark-gfm#53]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently, there are many different ways to express note/warning/information alert boxes. 

For example, from your own docs, this could be transformed into a GitHub note box:

> 👉 **Note**: before participating in our community, please read our
> [code of conduct][coc].

MDN searches for the following syntax to render an alert box:

> **Warning:** If you just see "1 3" instead of a fraction, then your browser may not support MathML.

### Solution

GitHub seems to have added a syntax for note/warning/info alert boxes to GFM. They render like this:

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

> [!IMPORTANT]  
> Crucial information necessary for users to succeed.

> [!WARNING]  
> Critical content demanding immediate user attention due to potential risks.

See https://github.com/orgs/community/discussions/16925

Will this be supported in remark-gfm?

### Alternatives

.

**Comment by remcohaszing** [comment]
`remark-gfm` is about adding GFM syntax. What you’re proposing, is to alter HTML output. This is out of scope for this project. It would be nice to have in https://github.com/rehypejs/rehype-github though.

**Comment by Elchi3** [comment]
> `remark-gfm` is about adding GFM syntax. 

Thanks, my understanding was that `> [!NOTE] `, `> [!IMPORTANT] ` and `> [!WARNING]`  is new GFM syntax.

> What you’re proposing, is to alter HTML output. This is out of scope for this project. It would be nice to have in https://github.com/rehypejs/rehype-github though.

Okay, I'm happy to file an issue there.

**Comment by remcohaszing** [comment]
Oh, I see they recently added a new syntax. Now I’m not entirely sure anymore.

**Comment by wooorm** [comment]
Hi!

> is new GFM syntax.

There are tons of features GH does on its platform to markup.
There are very few features part of GFM. Here is their GFM parser: https://github.com/github/cmark-gfm. It does not include this.
So remco is correct, this does not go here!

**Comment by LuudJanssen** [comment]
I created a Remark plugin to transform GitHub's syntax to the directives syntax used by admonitions: [remark-github-admonitions-to-directives](https://github.com/incentro-dc/remark-github-admonitions-to-directives)

**Comment by lilouartz** [comment]
Oh wow, thanks @LuudJanssen !

**Comment by iSpeakNerd** [comment]
this rehype plugin does what you want @Elchi3 
https://github.com/chrisweb/rehype-github-alerts
