### ISSUE TITLE
Support for chinese period separated in link.

### ISSUE THREAD

**Issue by lalawila** [remarkjs/remark-gfm#55]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

3.0.1

### Steps to reproduce
`
我们的官网是 https://www.x-ac.com。您可以在官网上了解更多关于我们的产品和服务信息。如果您有任何具体的问题或需求，我也可以尽力帮助您。
`
### Expected behavior
`
我们的官网是 <a href="https://www.x-ac.com">https://www.x-ac.com</a>。您可以在官网上了解更多关于我们的产品和服务信息。如果您有任何具体的问题或需求，我也可以尽力帮助您。
`
### Actual behavior
`
我们的官网是 <a href="https://www.x-ac.com。您可以在官网上了解更多关于我们的产品和服务信息。如果您有任何具体的问题或需求，我也可以尽力帮助您。">https://www.x-ac.com。您可以在官网上了解更多关于我们的产品和服务信息。如果您有任何具体的问题或需求，我也可以尽力帮助您。</a>
`

**Comment by wooorm** [comment]
That’s how GFM works:

```markdown
我们的官网是 https://www.x-ac.com/。您可以在官网上了解更多关于我们的产品和服务信息。如果您有任何具体的问题或需求，我也可以尽力帮助您。
```

我们的官网是 https://www.x-ac.com/。您可以在官网上了解更多关于我们的产品和服务信息。如果您有任何具体的问题或需求，我也可以尽力帮助您。

Use explicit markdown links:

```markdown
我们的官网是 [x-ac.com](https://www.x-ac.com/)。您可以在官网上了解更多关于我们的产品和服务信息。如果您有任何具体的问题或需求，我也可以尽力帮助您。
```

我们的官网是 [x-ac.com](https://www.x-ac.com/)。您可以在官网上了解更多关于我们的产品和服务信息。如果您有任何具体的问题或需求，我也可以尽力帮助您。


That’s much better, because you shouldn’t *show* the `http://www.` and `/` parts to users.
