### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by ylc395** [remarkjs/remark-gfm#56]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

All dependencies are outdated, so my package manager has to download extra version of these dependencies for this package. Maybe we can bump them to latest major version. 

### Solution

Update dependencies

### Alternatives

No

**Comment by wooorm** [comment]
Hey! See https://github.com/unifiedjs/unified/issues/228 and other issues.
There are 500+ projects. It takes time to update everything. I am working on it. I’ll get to it asap.
