### ISSUE TITLE
Pipe symbol `|` inside code inside table cell is parsed as table separator

### ISSUE THREAD

**Issue by remorses** [remarkjs/remark-gfm#60]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

remark-gfm@4

### Link to runnable example

https://stackblitz.com/edit/github-iglaql-z65qwa?file=src%2Fmain.ts

### Steps to reproduce

1. run vite
2. notice the output is different from input, the pipe symbol (`|`) is interpreted as a table separator instead of being inside the code block

### Expected behavior

A pipe operator inside an inline code should not be parsed as table separator

### Actual behavior

Pipe is parsed as table separator

### Runtime

Node v16

### Package manager

npm 8

**Comment by wooorm** [comment]
Yup, try it on GH:

```markdown
| a             |
| ---           |
| `'pipe' | and`|
```

| a             |
| ---           |
| `'pipe' | and`|

See? The stuff gets lost.
This is a known GH gotcha that we follow.
They solve it in a weird way, which we also do: you cannot normally escape in code, but you *can* escape pipes in cells in code:

```markdown
| a             |
| ---           |
| `'pipe' \| and`|
```

| a             |
| ---           |
| `'pipe' \| and`|

I wrote some more about all the parsing details of tables here: https://github.com/wooorm/markdown-rs/blob/main/src/construct/gfm_table.rs

**Comment by remorses** [comment]
Thank you! I didn't know that
