### ISSUE TITLE
Resizable columns for table

### ISSUE THREAD

**Issue by YashTrivedi21** [remarkjs/remark-gfm#61]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently remark-gfm doesn't support resizable column for tables, is there any plan to implement this in future?

### Solution

A prop that needs to be passed to enable resizable columns in the plugin such that user can drag the column widths, min width and max width can also be passed as a prop.

### Alternatives

Not without help of an extra library or code from scratch.

**Comment by wooorm** [comment]
There are many ways.
It doesn’t have anything to do with this project though.
Please ask a question in the designated support channels with much more info.
