### ISSUE TITLE
Cannot render table in remarkgfm

### ISSUE THREAD

**Issue by theadanielskocher** [remarkjs/remark-gfm#64]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

4.0.0

### Steps to reproduce

I try to type table syntax, but it cannot render the table.

### Expected behavior

Create a table.

### Actual behavior

It reload the page and clear all the data.

**Comment by ChristianMurphy** [comment]
@theadanielskocher welcome!
Tables are very thoroughly tested, it's unlikely to be tables are broken.
More likely there is a dependency conflict or incorrect usage of the library, but there isn't really enough info to help there either.

What are you trying as table syntax? How are you using the library? And what versions of dependencies are you using.

**Comment by theadanielskocher** [comment]
I don't know how to explain the error to you, so you can visit this website https://dbrr-markdown-editor.surge.sh/, you type the table syntax to this markdown editor to understand the error. Thank you so much for your reply!

```
| a | b |
| - | - |
| c | d |
```

**Comment by ChristianMurphy** [comment]
> I don't know how to explain the error to you

Don't explain it to me.
Share a runnable piece of source code with an example of the issue.

Here is a runnable example in a sandbox showing it working https://stackblitz.com/edit/github-zyfw4s?file=src%2Fapp.tsx
This follows the instructions from https://github.com/remarkjs/react-markdown?tab=readme-ov-file#use on how to setup GFM.

> so you can visit this website https://dbrr-markdown-editor.surge.sh/

See the support guidelines https://github.com/remarkjs/.github/blob/main/support.md
If you don't share any source, there isn't much help myself or anyone else can offer.

---

I'm closing this, as the sandbox above shows it isn't a bug in `remark-gfm`, the issue tracker is for bug and feature requests which are actionable.
If you have questions on how to leverage `react-markdown` or `remark-gfm` feel free to ask them in the forum https://github.com/orgs/remarkjs/discussions folks are happy to help!
