### ISSUE TITLE
Support for merged cells

### ISSUE THREAD

**Issue by Startouf** [remarkjs/remark-gfm#66]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Show table with merged cells (like one header row spanning over two cells)

Currently the following syntax does not work

```markdown
| **Header spanning two columns ||
| - ||
| column 1 | column 2|
```

Note that Github does not seem to suport this either : 

| **Header spanning two columns ||
| - ||
| column 1 | column 2|

### Solution

Support syntaxes allowing t create merged cells

See specs and questions asked on StackOverflow

https://web.archive.org/web/20170905052152/http://fletcher.github.io/MultiMarkdown-5/tables.html
https://stackoverflow.com/questions/46621765/can-i-merge-table-rows-in-markdown

### Alternatives

Support pandoc style markdown for tables ? 
https://pandoc.org/chunkedhtml-demo/8.9-tables.html

**Comment by wooorm** [comment]
Hey! This project is called `remark-gfm`, not `remark-multimarkdown` or `remark-pandoc`, so nope, not going to happen.

I recommend not doing this. Use regular GFM tables. Or, use HTML.

**Comment by Damola18** [comment]
> Hey! This project is called `remark-gfm`, not `remark-multimarkdown` or `remark-pandoc`, so nope, not going to happen.
> 
> I recommend not doing this. Use regular GFM tables. Or, use HTML.

So are you at any point considering adding support for row spanning or column spacing in the future. If not, what alternatives do you have in place for tables with merged cells for remark-gfm ?. Tried a handful of things for my current use case but it doesnt seem to work.

**Comment by ChristianMurphy** [comment]
Hey @Damola18! 👋 

Taking a step back, consider not creating another markdown flavor.
The reasons and alternatives are explained best here: https://github.com/micromark/micromark?tab=readme-ov-file#extending-markdown

> So are you at any point considering adding support for row spanning or column spacing in the future

Not to remark-gfm, no.

> If not, what alternatives do you have in place for tables with merged cells for remark-gfm ?. 

None in remark-gfm

> Tried a handful of things for my current use case but it doesnt seem to work.

It is possible to create your own markdown extension for pandoc or any other flavor you want to support.
https://github.com/micromark/micromark?tab=readme-ov-file#creating-a-micromark-extension
the process is involved, but possible.
