### ISSUE TITLE
Add support for Alerts

### ISSUE THREAD

**Issue by tukusejssirs** [remarkjs/remark-gfm#67]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The [Alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) feature is not properly parsed ATM.

The issue is that `> [!NOTE]` is converted to `> \[!NOTE]` (`[` is escaped) which is an invalid Alert syntax.

Here are all possible alert types currently supported by GFM:

```md
> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.
```

### Solution

`> [!NOTE]` (and other alert types) should be left intact.

### Alternatives

Of course, can remove the backslashes using `String(file).replace(/^> \\\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\][ \t]*$/gm, '> [!$1]')`, however, I think `remark-gfm` should support this out of box. :wink:

**Comment by remcohaszing** [comment]
GitHub looks at the textual meaning of the blockquote content. It works fine with escaped `[` characters.

---

```markdown
> \[!NOTE]
> Useful information that users should know, even when skimming content.
```

yields:

> \[!NOTE]
> Useful information that users should know, even when skimming content.

---

```markdown
> [!NOTE]
> Useful information that users should know, even when skimming content.

[!note]: https://example.com
```

yields:

> [!NOTE]
> Useful information that users should know, even when skimming content.

[!note]: https://example.com

**Comment by tukusejssirs** [comment]
Thanks for taking the time to reply to my issue! :pray:

Exactly, it _does not_ work as expected. :wink:

![image](https://github.com/remarkjs/remark-gfm/assets/5111894/445d757e-b6fc-4db3-a2aa-fefc0d85c712)

**Comment by wooorm** [comment]
```markdown
> [!NOTE]
Some note

[!note]: https://example.com
```

Yields:

> [!NOTE]
Some note

[!note]: https://example.com

**Comment by wooorm** [comment]
I am not sure our projects here should change —— GH made a new format that interferes with references/definitions. We consider those references/definitions too. That’s why they get escaped

**Comment by tukusejssirs** [comment]
> I am not sure our projects here should change.

@wooorm, well if the package name includes `gfm`, thus you try to support GitHub Flavored Markdown, I think it is fair to expect your goal is to support all GFM features.

That said, I see that [here](https://github.github.com/gfm/) the GFM spec is only `v0.29-gfm` from 6 Apr 2019 and it does not include the alerts feature, so you might say you don’t want to add anything outside of the (latest) published spec of GFM which is fine.

> GH made a new format that interferes with references/definitions.

Does it interfere? This new feature has a strict format ([`/^> {0,4}\[!(NOTE|TIP|IMPORTANT|WARNING|CAUTION)\](\n> *.*)+$/gm`](https://regex101.com/r/KEAwHe/1)) which could be made an exception to the references/definitions format. Anyway, is `[!NOTE]` a valid reference/definition format? It could be if one defines such reference, however can it start with an exclamation mark? :thinking: Even if it can, the alerts are so strict about the formatting the alert types, it should be a big issue IMHO. That said, you know the plugin’s codebase better. :wink:

**Comment by wooorm** [comment]
As you found out, notes aren’t GFM.
GFM is several syntax extensions to markdown that work everywhere on GitHub.
This isn’t a syntax extension.
This is AST transforms on the HTML.
GH does many things to your content that aren’t GFM.

> Does it interfere?
> Anyway, is [!NOTE] a valid reference/definition format

Yep, I just showed that: https://github.com/remarkjs/remark-gfm/issues/67#issuecomment-2198492600

> The alerts are so strict about the formatting the alert types

They’re loose enough to allow that escaped `[`. It works, this project makes markdown that works?

**Comment by wooorm** [comment]
You might enjoy this example:

```markdown
<blockquote>
<p>[!NOTE]
asd</p>
</blockquote>
```

<blockquote>
<p>[!NOTE]
asd</p>
</blockquote>

**Comment by tukusejssirs** [comment]
Okay, @wooorm, thanks for your time. :pray:

Indeed it works as expected even with `\[!NOTE]`. Now I think it might be even better to keep it as is, as it lets references work in all cases.

> You might enjoy this example:

When I write Markdown, I prefer not inserting HTML code unless there is a big requirement to do so. However, thanks for sharing this! :pray:

---

Feel free to close this issue. :wink:

**Comment by wooorm** [comment]
ok, closing! :+1:

>  I prefer not inserting HTML code

Right right! No, I meant to show this as it illustrtrates how GH works! They also accept this HTML. They don’t give a hoot about the original markdown of the `[!NOTE]`!

**Comment by theking2** [comment]
both

```md
> [!NOTE]
this is informational
```

and


```md
> [!NOTE]
> this is informational
```

yield

> [!NOTE]
this is informational

at least here

**Comment by wooorm** [comment]
yep, that’s how lazy blockquote lines work!
