### ISSUE TITLE
Tables missing align="center" support

### ISSUE THREAD

**Issue by dsernst** [remarkjs/remark-gfm#68]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

4.0.0

### Steps to reproduce

```markdown
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
```

(from example in bottom right corner of https://www.tablesgenerator.com/markdown_tables)

### Expected behavior

Demo'ing left, center, and right alignment:

| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |

### Actual behavior

Everything left aligned:

| Tables   |      Are      |  Cool |
|----------|-------------|------|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |

**Comment by ChristianMurphy** [comment]
Welcome @dsernst! 👋 
It is supported, you can see an example of it working here.

https://stackblitz.com/edit/github-xvqrna?file=src%2Fmain.ts

You are either not using `remark-gfm` or may have a version or configuration issue.
Please update all your remark related dependencies to latest.
If the issue persists, please share a runnable reproduction so others can assist.

**Comment by dsernst** [comment]
Ok, thanks for the quick reply and working example.

I now see there is a `param.style.textAlign: center` being passed down for the component to use.

You were right! Thanks
