### ISSUE TITLE
Regex issues in safari 16 (iOS) and below

### ISSUE THREAD

**Issue by KenjiEmura** [remarkjs/remark-gfm#69]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

4.0.0

### Steps to reproduce

I'm using `remark-gfm` in a Next.js project and the library is making the project crash on devices running iOS 16 and below. As far as my research went, it seems to be something related to the `lookbehind` or `lookahead` methods for regex which are supported from safari 16.4 and above.

I would like to kindly ask if you could also include support for safari 15 and above or if you can show me a workaround to solve this issue. Thanks a lot.

### Expected behavior

The package should have some kind of fallback for regex methods that are not supported in the runtime.

### Actual behavior

The unhandled missing methods make the application crash.

### Package manager

pnpm

### OS

Other (please specify in steps to reproduce)

### Build and bundle tools

Next.js

**Comment by nguyenchauhuyen** [comment]
any update ? i am facing the same problem
