### ISSUE TITLE
Strikethroughs are not rendered

### ISSUE THREAD

**Issue by nmattia** [remarkjs/remark-gfm#71]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=issues) and [discussions](https://github.com/orgs/remarkjs/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

remark-gfm@4.0.0

### Steps to reproduce

I've adapted the function from the README to parse markdown with strikethrough (both single & double tildes):

```ts
async function test() {

  const file = await unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkRehype)
    .use(rehypeStringify)
    .process(`
## Strikethrough

~one~ or ~~two~~ tildes.
            `);

  console.log(String(file))
}

test();
```

Running the program does not render `<del>` elements:

```
<h2>Strikethrough</h2>
<p>~one~ or ~~two~~ tildes.</p>
```

Happening inside an astro project, though doubt that has an impact:

```
$ npm list
@nmattia/nmattia.com@0.0.1 /Users/nicolas/nmattia.com
├── @astrojs/check@0.9.4
├── @astrojs/markdown-remark@6.0.0
├── @astrojs/rss@4.0.10
├── @astrojs/sitemap@3.2.1
├── @types/hast@3.0.4
├── astro@5.0.3
├── hast-util-classnames@3.0.0
├── hast-util-is-element@3.0.0
├── prettier-plugin-astro@0.14.1
├── prettier@3.3.3
├── rehype-document@7.0.3
├── rehype-format@5.0.1
├── rehype-katex@6.0.3
├── rehype-raw@7.0.0
├── remark-gfm@4.0.0
├── remark-math@6.0.0
├── the-new-css-reset@1.8.4
├── typescript@5.5.4
└── unist-util-visit@5.0.0
```

### Actual behavior

The output does not include `<del>` elements:

```
<h2>Strikethrough</h2>
<p>~one~ or ~~two~~ tildes.</p>
```

### Expected behavior

By default both single and double tildes should be rendered as `del` elements:

```
<h2>Strikethrough</h2>
<p><del>one</del> or <del>two</del> tildes.</p>
```

**Comment by wooorm** [comment]
Hi Nicolas! Tests work here. So I assume that this is an Astro problem. Or you have out of date dependencies.

**Comment by nmattia** [comment]
@wooorm thanks! I'll dig a bit deeper then and report back

**Comment by nmattia** [comment]
Finally circled back to this, and just for the record: looks like everything works now! I updated a bunch of dependencies over the past 6 months (including astro itself), I'm guessing you were right @wooorm  :)

> So I assume that this is an Astro problem. Or you have out of date dependencies.
