### ISSUE TITLE
Ordered list is not rendered as expected using react-markdown and remark-gfm plugin

### ISSUE THREAD

**Issue by gilisho** [remarkjs/remark-gfm#9]
### Subject of the issue

I have users who want to render some content in an ordered list. The content looks good in Github, but when I render it with `react-markdown` using the `remark-gfm` plugin, it gets rendered wrong and the whole list is not looking as expected.

### Your environment

*   **Packages**: `react-markdown` (version 5)

### Steps to reproduce

Example in `codesandbox.io`:
https://codesandbox.io/s/react-markdown-forked-v6iy7?file=/src/App.js

### Expected behavior

Should render the ordered list exactly like in Github:
```
1. some text
some link
2. Number two
```

### Actual behavior

![image](https://user-images.githubusercontent.com/40733156/108207720-cb69a780-7130-11eb-93b9-20108782cfa6.png)

**Comment by wooorm** [comment]
Thanks for the report. It seems to be https://github.com/remarkjs/remark-gfm/issues/3

**Comment by wooorm** [comment]
Going to close this to direct the conversation and work to GH-3.

**Comment by kacem22** [comment]
```js
<ReactMarkdown
  components={{
    ul: ({ node, ...props }) => (
      <ul
        style={{
          display: "block",
          listStyleType: "disc",
          paddingInlineStart: "40px",
        }}
        {...props}
      />
    ),
    ol: ({ node, ...props }) => (
      <ol
        style={{
          display: "block",
          listStyleType: "decimal",
          paddingInlineStart: "40px",
        }}
        {...props}
      />
    ),
  }}
>{markdown}</ReactMarkdown>
```
